# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'HHNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HHNews
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'MJRefresh'
  pod 'RxCocoa'
  
  # 网络图片库
  pod 'Kingfisher'

  target 'HHNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HHNewsUITests' do
    # Pods for testing
  end

end
